import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/provider/theme-provider";
import { ThemeScript } from "@/components/ui/theme-script";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${roboto.variable} antialiased`}
      suppressHydrationWarning={true}
    >
      <head>
        <ThemeScript storageKey="vietlegal-theme" />
      </head>
      <body>
        <ThemeProvider defaultTheme="dark" storageKey="vietlegal-theme">
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
