import type { Metadata } from "next";
import { Noto_Sans } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/provider/theme-provider";
import { ThemeScript } from "@/components/ui/theme-script";

const notoSans = Noto_Sans({
  variable: "--font-noto-sans",
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "500", "600", "700"],
});

// const inter = Inter({
//   variable: "--font-inter",
//   subsets: ["latin"],
// });

// const playfairDisplay = Playfair_Display({
//   variable: "--font-playfair-display",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${notoSans.variable} antialiased`}
      suppressHydrationWarning
    >
      <head>
        <ThemeScript storageKey="vietlegal-theme" />
      </head>
      <body>
        <ThemeProvider defaultTheme="dark" storageKey="vietlegal-theme">
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
